/**
 * Created by jiangyukun on 2016/11/2.
 */

export default {
    CONN_OPENED: 'CONN_OPENED',
    CONN_OPENING: 'CONN_OPENING',
    CONN_UN_OPEN: 'CONN_UN_OPEN',
    CONN_RE_OPEN: 'CONN_RE_OPEN',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_FAILURE_RESET: 'LOGIN_FAILURE_RESET',

    EXIT_CHAT_SYSTEM: 'EXIT_CHAT_SYSTEM',

    CHECK_LOGIN_INFO: 'CHECK_LOGIN_INFO',
    LOGIN_OUT: 'LOGIN_OUT',
    SEND_TEXT_MESSAGE: 'SEND_TEXT_MESSAGE',
    READ_MESSAGE: 'READ_MESSAGE',
    SEND_IMAGE_MESSAGE: 'SEND_IMAGE_MESSAGE',
    SEND_AUDIO_MESSAGE: 'SEND_AUDIO_MESSAGE',
    BEGIN_USER_CHAT: 'BEGIN_USER_CHAT',
    BEGIN_GROUP_CHAT: 'BEGIN_GROUP_CHAT',
    FETCH_HISTORY_MESSAGE: 'FETCH_HISTORY_MESSAGE',

    message: {
        NEW_MSG: 'NEW_MSG',
        FETCH_HISTORY_MESSAGE_SUCCESS: 'FETCH_HISTORY_MESSAGE_SUCCESS'
    },

    chat: {
        INIT_PATIENT_START: 'INIT_PATIENT_START',
        INIT_PATIENT_SUCCESS: 'INIT_PATIENT_SUCCESS',
        INIT_PATIENT_FAILURE: 'INIT_PATIENT_FAILURE',

        INIT_GROUP_START: 'INIT_GROUP_START',
        INIT_GROUP_SUCCESS: 'INIT_GROUP_SUCCESS',
        INIT_GROUP_FAILURE: 'INIT_GROUP_FAILURE',

        INIT_DOCTOR_START: 'INIT_DOCTOR_START',
        INIT_DOCTOR_SUCCESS: 'INIT_DOCTOR_SUCCESS',
        INIT_DOCTOR_FAILURE: 'INIT_DOCTOR_FAILURE',

        START_SINGLE_CHAT: 'START_SINGLE_CHAT',
        START_GROUP_CHAT: 'START_GROUP_CHAT',

        READ_SINGLE_MESSAGE: 'READ_SINGLE_MESSAGE',

        FETCH_GROUP_MEMBER_SUCCESS: 'FETCH_GROUP_MEMBER_SUCCESS'
    }
}
